- updated

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -15,6 +15,35 @@ then
     exit 1
 fi
 
+
+# config=commit-msg.config.json
+
+# # set variables
+# enabled=$(jq -r .enabled $config)
+# revert=$(jq -r .revert $config)
+# types=($(jq -r '.types[]' $config))
+# min_length=$(jq -r .length.min $config)
+# max_length=$(jq -r .length.max $config)
+
+# if [[ ! -f $config || ! $enabled ]]; then
+#     exit 0
+# fi
+
+
+
+
+# msg=$(head -1 $1)
+# if [[ ! $msg =~ $regexp ]]; then
+#   echo -e "\n\e[1m\e[31m[INVALID COMMIT MESSAGE]"
+#   echo -e "------------------------\033[0m\e[0m"
+#   echo -e "\e[1mValid types:\e[0m \e[34m${types[@]}\033[0m"
+#   echo -e "\e[1mMax length (first line):\e[0m \e[34m$max_length\033[0m"
+#   echo -e "\e[1mMin length (first line):\e[0m \e[34m$min_length\033[0m\n"
+
+#   # exit with an error
+#   exit 1
+# fi
+
 # exit 0
 # exec git diff-index --check --cached $against --
 
